### PR TITLE
there was 2 name

### PR DESCRIPTION
**Pull request by Zimquadery**

### CODE REVIEW

**Comment by TheCodeHeist** [comment]
I don't really need this bot!

**Comment by Zimquadery** [comment]
Tomar khobor ki? Shusto hoiso? Discord a dekhi na koydin holo

**Comment by TheCodeHeist** [comment]
Ji ami sustho...but ami discord-e dhuka komay disi! Emon ki bhondhu-der shatheo kotha boli na!

**Comment by Zimquadery** [comment]
Keno! Ki hoise?

**Comment by Zimquadery** [comment]
Eid er por ki active thakte parba? Coding para badly needs you.

**Pull request closed without merging**
